version: '3'

services:
  poll:
    restart: on-failure
    build: ./poll
    depends_on:
      - redis
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    networks:
      - poll-tier

  redis:
    restart: on-failure
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    restart: on-failure
    build: ./worker
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - back-tier

  db:
    restart: on-failure
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data

  result:
    restart: on-failure
    build: ./result
    depends_on:
      - db
    ports:
      - "5001:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
