name: bonus
version: 0.1.0.0
dependencies:
- base >= 4.7 && < 5
- random >= 1.2.0
- JuicyPixels >= 3.3.5
- parallel >= 3.2.0
- deepseq >= 1.4.4
- containers >= 0.6.0

library:
  source-dirs: src
  exposed-modules:
  - Error
  - Validators
  - Config
  - FileParsing
  - Distance
  - Clustering
  - Centroids
  - Reconstruction

executables:
  bonus:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -Wcompat
    dependencies:
    - bonus
